/**
 * 从 TypeScript 类型自动生成 OpenAPI 兼容的 JSON Schema
 * 使用 ts-json-schema-generator 解析 types.ts
 *
 * This file is almost fully generated by AI，FFBox 作者对此代码的正确性不做保证 :-)
 */
const fs = require('fs');
const path = require('path');

// 动态导入 ts-json-schema-generator (ESM 模块)
async function main() {
	const { createGenerator } = await import('ts-json-schema-generator');

	const typesPath = path.resolve(__dirname, '../src/common/types.ts');
	const tsconfigPath = path.resolve(__dirname, '../tsconfig.json');
	const outputPath = path.resolve(__dirname, '../docs/schemas.json');

	console.log('正在从 TypeScript 类型生成 JSON Schema...');
	console.log('源文件:', typesPath);

	// 需要导出的类型列表（按类别组织）
	const typesToExport = [
		// 核心类型
		'Task',
		'Notification',
		'NotificationLevel',
		'FFBoxVersion',
		'FFmpegInfo',
		'FFmpegProgress',

		// 输出参数相关
		'OutputParams',
		'OutputParams_input',
		'OutputParams_filter',
		'OutputParams_video',
		'OutputParams_audio',
		'OutputParams_mux',
		'OutputParams_extra',
		'InputFile',
		'FilterNode',
		'FilterLine',

		// 输入信息相关
		'InputInfo',
		'StreamInfo',
		'ChapterInfo',

		// FFmpeg 编解码器相关
		'EncoderDetail',
		'FFmpegCodecDetail',
		'FFmpegMuxerDetail',
		'FFmpegFilterDetail',

		// 任务相关
		'TaskStatus',
		'SingleProgressLog',

		// Webhook 相关
		'TaskEventType',
		'QueueEventType',
		'TaskListEventType',
		'NotificationEventType',
		'WebhookEventType',
		'WebhookFilter',
		'Webhook',
		'WebhookEventDataMap',
		'WebhookPayload',
		'CreateWebhookRequest',
		'UpdateWebhookRequest',
	];

	// 创建生成器
	const generator = createGenerator({
		path: typesPath,
		tsconfig: tsconfigPath,
		skipTypeCheck: true,
	});

	// 为每个类型生成 schema
	const schemas = {};

	for (const typeName of typesToExport) {
		try {
			const schema = generator.createSchema(typeName);
			if (schema.definitions && schema.definitions[typeName]) {
				// 提取该类型的定义
				schemas[typeName] = schema.definitions[typeName];
				// 也提取依赖的类型定义
				for (const [name, def] of Object.entries(schema.definitions)) {
					if (name !== typeName && !schemas[name]) {
						schemas[name] = def;
					}
				}
			}
		} catch (err) {
			console.warn(`警告: 无法生成类型 "${typeName}" 的 schema:`, err.message);
		}
	}

	// 后处理：转换为 OpenAPI 兼容格式
	const openApiSchemas = convertToOpenApiSchemas(schemas);

	// 确保输出目录存在
	fs.mkdirSync(path.dirname(outputPath), { recursive: true });

	// 写入文件
	fs.writeFileSync(outputPath, JSON.stringify(openApiSchemas, null, 2), 'utf-8');

	console.log(`成功生成 ${Object.keys(openApiSchemas).length} 个 schema`);
	console.log('输出文件:', outputPath);
}

/**
 * 将 JSON Schema 转换为 OpenAPI 兼容格式
 * OpenAPI 使用 $ref: '#/components/schemas/X' 格式
 */
function convertToOpenApiSchemas(schemas) {
	const result = {};

	for (const [name, schema] of Object.entries(schemas)) {
		// 跳过内部类型（如 __type 等）
		if (name.startsWith('__')) continue;

		result[name] = convertSchema(schema, name);
	}

	return result;
}

/**
 * 递归转换 schema，处理 $ref 格式
 */
function convertSchema(schema, typeName) {
	if (!schema || typeof schema !== 'object') return schema;

	const result = {};

	for (const [key, value] of Object.entries(schema)) {
		if (key === '$ref') {
			// JSON Schema: #/definitions/X -> OpenAPI: #/components/schemas/X
			const match = value.match(/^#\/definitions\/(.+)$/);
			if (match) {
				result['$ref'] = `#/components/schemas/${match[1]}`;
			} else {
				result[key] = value;
			}
		} else if (key === 'definitions') {
			// 跳过内联 definitions，已在外层处理
			continue;
		} else if (typeof value === 'object' && value !== null) {
			if (Array.isArray(value)) {
				result[key] = value.map(item =>
					typeof item === 'object' ? convertSchema(item, typeName) : item
				);
			} else {
				result[key] = convertSchema(value, typeName);
			}
		} else {
			result[key] = value;
		}
	}

	return result;
}

main().catch(err => {
	console.error('生成失败:', err);
	process.exit(1);
});