name: Fetch GitHub Releases

on:
  schedule:
    - cron: '0 * * * *' # 每小时运行一次
  workflow_dispatch:     # 允许手动触发

jobs:
  update-releases:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: git fetch pull 和 curl GitHub API
        run: |
          git fetch
          git pull
          curl -s https://api.github.com/repos/ttqftech/FFBox/releases > public/releases.json
          cp public/releases.json docs/releases.json

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/releases.json
          git commit -m "Update releases.json [auto]" || echo "No changes to commit"
          git push
